using System.Diagnostics;
using System.Net.NetworkInformation;
using System.ServiceProcess;
using System.Text;

namespace CodeName399.ServerSetupManager;

internal static class Program
{
    [STAThread] static void Main(){ ApplicationConfiguration.Initialize(); Application.Run(new MainForm()); }
}

public sealed record ServiceDef(string Name,string Project,string Folder,string Service,int Port,string Exe);

public sealed class MainForm : Form
{
    TextBox source=new(), server=new(), nginx=new(), uiSource=new(); RichTextBox log=new();
    readonly List<ServiceDef> services = new(){
      new("Gateway","CodeName399.Gateway\\CodeName399.Gateway.csproj","Gateway","CodeName399.Gateway",5000,"CodeName399.Gateway.exe"),
      new("Auth","CodeName399.Auth.API\\CodeName399.Auth.API.csproj","Auth","CodeName399.Auth",5001,"CodeName399.Auth.API.exe"),
      new("KuberX","CodeName399.KuberX.API\\CodeName399.KuberX.API.csproj","KuberX","CodeName399.KuberX",5004,"CodeName399.KuberX.API.exe"),
      new("Instrument","CodeName399.Instrument.API\\CodeName399.Instrument.API.csproj","Instrument","CodeName399.Instrument",5101,"CodeName399.Instrument.API.exe"),
      new("HistoricalCandles","CodeName399.HistoricalCandles.API\\CodeName399.HistoricalCandles.API.csproj","HistoricalCandles","CodeName399.HistoricalCandles",5102,"CodeName399.HistoricalCandles.API.exe"),
      new("Evaluation","CodeName399.Evaluation.API\\CodeName399.Evaluation.API.csproj","Evaluation","CodeName399.Evaluation",5103,"CodeName399.Evaluation.API.exe"),
      new("VirtualTrading","CodeName399.VirtualTrading.API\\CodeName399.VirtualTrading.API.csproj","VirtualTrading","CodeName399.VirtualTrading",5104,"CodeName399.VirtualTrading.API.exe"),
      new("Buying","CodeName399.Buying.API\\CodeName399.Buying.API.csproj","Buying","CodeName399.Buying",5105,"CodeName399.Buying.API.exe"),
      new("Selling","CodeName399.Selling.API\\CodeName399.Selling.API.csproj","Selling","CodeName399.Selling",5106,"CodeName399.Selling.API.exe"),
      new("StockPerformance","CodeName399.StockPerformance.API\\CodeName399.StockPerformance.API.csproj","StockPerformance","CodeName399.StockPerformance",5107,"CodeName399.StockPerformance.API.exe"),
      new("Optimization","CodeName399.Optimization.API\\CodeName399.Optimization.API.csproj","Optimization","CodeName399.Optimization",5108,"CodeName399.Optimization.API.exe"),
      new("EquityTrading","CodeName399.EquityTrading.API\\CodeName399.EquityTrading.API.csproj","EquityTrading","CodeName399.EquityTrading",5109,"CodeName399.EquityTrading.API.exe"),
      new("FutureTrading","CodeName399.FutureTrading.API\\CodeName399.FutureTrading.API.csproj","FutureTrading","CodeName399.FutureTrading",5110,"CodeName399.FutureTrading.API.exe"),
      new("OptionsTrading","CodeName399.OptionsTrading.API\\CodeName399.OptionsTrading.API.csproj","OptionsTrading","CodeName399.OptionsTrading",5111,"CodeName399.OptionsTrading.API.exe"),
      new("Email","CodeName399.Email.API\\CodeName399.Email.API.csproj","Email","CodeName399.Email",5112,"CodeName399.Email.API.exe")};
    readonly Dictionary<string,CheckBox> selected=new(); readonly Dictionary<string,Label> states=new();
    Button fullSetup=null!, build=null!, publish=null!, restart=null!, nginxBtn=null!, uiDeploy=null!; CancellationTokenSource? cts;

    public MainForm(){
      Text="CodeName399 Server Setup Manager"; Width=1300; Height=850; MinimumSize=new(1050,700); StartPosition=FormStartPosition.CenterScreen; Font=new("Segoe UI",9);
      var top=new TableLayoutPanel{Dock=DockStyle.Top,Height=165,ColumnCount=3,RowCount=4,Padding=new(10)}; top.ColumnStyles.Add(new(SizeType.Absolute,120));top.ColumnStyles.Add(new(SizeType.Percent,100));top.ColumnStyles.Add(new(SizeType.Absolute,110));
      AddPath(top,0,"Source",source,Environment.GetEnvironmentVariable("CODENAME399_SOURCE")??@"C:\Users\gauda\source\repos\codename399\CodeName399.API"); AddPath(top,1,"Server Root",server,@"C:\Servers\CodeName399"); AddPath(top,2,"Nginx EXE",nginx,@"C:\nginx\nginx.exe");
      var browse1=Btn("Browse",(_,_)=>BrowseFolder(source)); var browse2=Btn("Browse",(_,_)=>BrowseFolder(server)); var browse3=Btn("Browse",(_,_)=>BrowseFile(nginx)); top.Controls.Add(browse1,2,0);top.Controls.Add(browse2,2,1);top.Controls.Add(browse3,2,2); AddPath(top,3,"Angular UI",uiSource,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"source","repos","codename399","home")); var browse4=Btn("Browse",(_,_)=>BrowseFolder(uiSource)); top.Controls.Add(browse4,2,3);
      var main=new SplitContainer{Dock=DockStyle.Fill,SplitterDistance=520,Padding=new(10)};
      var left=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3};left.RowStyles.Add(new(SizeType.Absolute,42));left.RowStyles.Add(new(SizeType.Percent,100));left.RowStyles.Add(new(SizeType.Absolute,150));
      var all=new CheckBox{Text="Select All Microservices",AutoSize=true,Font=new(Font,FontStyle.Bold),Margin=new(6)}; all.Text="Select All"; all.CheckedChanged+=(_,_)=>{foreach(var c in selected.Values)c.Checked=all.Checked;};left.Controls.Add(all,0,0);
      var list=new TableLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,ColumnCount=3,Padding=new(8),GrowStyle=TableLayoutPanelGrowStyle.AddRows,CellBorderStyle=TableLayoutPanelCellBorderStyle.Single};list.ColumnStyles.Add(new(SizeType.Absolute,38));list.ColumnStyles.Add(new(SizeType.Percent,100));list.ColumnStyles.Add(new(SizeType.Absolute,190));
      foreach(var s in services){var cb=new CheckBox{AutoSize=true,Margin=new(4)};selected[s.Name]=cb;var l=new Label{Text=s.Name,AutoSize=true,Anchor=AnchorStyles.Left,Margin=new(4,8,4,4)};var st=new Label{Text="Checking...",AutoSize=true,Anchor=AnchorStyles.Left,Margin=new(4,8,4,4)};states[s.Name]=st;list.Controls.Add(cb);list.Controls.Add(l);list.Controls.Add(st);}
      var uiCb=new CheckBox{AutoSize=true,Margin=new(4)}; selected["Angular UI"]=uiCb; var uiLabel=new Label{Text="Angular UI",AutoSize=true,Anchor=AnchorStyles.Left,Margin=new(4,8,4,4),Font=new(Font,FontStyle.Bold)}; var uiState=new Label{Text="NOT DEPLOYED",AutoSize=true,Anchor=AnchorStyles.Left,Margin=new(4,8,4,4)}; states["Angular UI"]=uiState; list.Controls.Add(uiCb); list.Controls.Add(uiLabel); list.Controls.Add(uiState);
      left.Controls.Add(list,0,1);
      var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,AutoScroll=true};
      fullSetup=Btn("FULL SETUP",async(_,_)=>await FullSetup()); build=Btn("Build Solution",async(_,_)=>await Run("dotnet",$"build \"{Sln}\" -c Release --no-restore","Build")); publish=Btn("Publish Selected",async(_,_)=>await PublishSelected()); restart=Btn("Restart All",async(_,_)=>await RestartAll()); nginxBtn=Btn("Configure / Restart Nginx",async(_,_)=>await ConfigureNginx()); uiDeploy=Btn("Build & Deploy Angular UI",async(_,_)=>await BuildDeployUi());
      foreach(var b in new[]{fullSetup,build,publish,uiDeploy,restart,nginxBtn,Btn("Stop Selected",async(_,_)=>await StopSelected()),Btn("Refresh Status",async(_,_)=>await RefreshStatus()),Btn("Clear Log",(_,_)=>log.Clear())})actions.Controls.Add(b);left.Controls.Add(actions,0,2);main.Panel1.Controls.Add(left);
      var right=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2};right.RowStyles.Add(new(SizeType.Absolute,40));right.RowStyles.Add(new(SizeType.Percent,100));right.Controls.Add(new Label{Text="Live Setup / Deployment Log",Font=new(Font,FontStyle.Bold),AutoSize=true,Margin=new(5,10,0,0)},0,0);log.Dock=DockStyle.Fill;log.ReadOnly=true;log.Font=new("Consolas",9);log.BackColor=Color.FromArgb(20,22,26);log.ForeColor=Color.Gainsboro;right.Controls.Add(log,0,1);main.Panel2.Controls.Add(right);
      Controls.Add(main);Controls.Add(top);Shown+=async(_,_)=>await RefreshStatus();
    }
    string Source=>source.Text.Trim(); string Server=>server.Text.Trim(); string UiSource=>uiSource.Text.Trim(); string Sln=>Path.Combine(Source,"CodeName399.sln");
    void AddPath(TableLayoutPanel t,int row,string label,TextBox box,string value){box.Text=value;box.Dock=DockStyle.Fill;t.Controls.Add(new Label{Text=label,AutoSize=true,Anchor=AnchorStyles.Left},0,row);t.Controls.Add(box,1,row);}
    Button Btn(string text,EventHandler e){var b=new Button{Text=text,AutoSize=true,Height=34,MinimumSize=new(105,34),Margin=new(4)};b.Click+=e;return b;}
    void BrowseFolder(TextBox t){using var d=new FolderBrowserDialog{SelectedPath=t.Text};if(d.ShowDialog()==DialogResult.OK)t.Text=d.SelectedPath;} void BrowseFile(TextBox t){using var d=new OpenFileDialog{Filter="Executable (*.exe)|*.exe"};if(d.ShowDialog()==DialogResult.OK)t.Text=d.FileName;}
    void Write(string s,bool err=false){if(InvokeRequired){BeginInvoke(()=>Write(s,err));return;}log.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}\n");log.SelectionStart=log.TextLength;log.ScrollToCaret();}
    void Busy(bool b){foreach(var c in Controls.OfType<Control>().SelectMany(Flatten).OfType<Button>())c.Enabled=!b;} IEnumerable<Control> Flatten(Control c)=>c.Controls.Cast<Control>().SelectMany(x=>new[]{x}.Concat(Flatten(x)));
    async Task BuildDeployUi(){Busy(true);try{if(!Directory.Exists(UiSource))throw new Exception("Angular UI source directory not found: "+UiSource); if(!File.Exists(Path.Combine(UiSource,"package.json")))throw new Exception("package.json not found in Angular UI source."); Directory.CreateDirectory(Path.Combine(Server,"UI")); Write("=== ANGULAR UI BUILD & DEPLOY STARTED ==="); await Run("npm","ci",UiSource,"UI"); var rc=await Run("npm","run build -- --configuration production",UiSource,"UI",false); if(rc!=0) rc=await Run("ng","build --configuration production",UiSource,"UI",false); if(rc!=0) throw new Exception("Angular production build failed."); var dist=FindAngularDist(UiSource); if(dist==null)throw new Exception("Angular build completed but dist output was not found."); await Run("robocopy", $"\"{dist}\" \"{Path.Combine(Server, "UI")}\" /E /R:2 /W:1", UiSource, "UI", false); Write("[UI] Files deployed to "+Path.Combine(Server,"UI")); await ConfigureNginx(); states["Angular UI"].Text="DEPLOYED • NGINX RUNNING"; Write("=== ANGULAR UI DEPLOYMENT SUCCESSFUL ===");}catch(Exception ex){Write("[ERROR] "+ex.Message,true);MessageBox.Show(ex.Message,"UI deployment failed",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{Busy(false);await RefreshStatus();}}
    string? FindAngularDist(string root){var dist=Path.Combine(root,"dist");if(!Directory.Exists(dist))return null;var idx=Directory.GetFiles(dist,"index.html",SearchOption.AllDirectories).FirstOrDefault();return idx==null?null:Path.GetDirectoryName(idx);}
    async Task FullSetup(){if(cts!=null)return;cts=new();Busy(true);try{Write("=== FULL SERVER SETUP STARTED ===");if(!Directory.Exists(Source))throw new Exception("Source directory not found: "+Source);if(!File.Exists(Sln))throw new Exception("Solution not found: "+Sln);Directory.CreateDirectory(Server);foreach(var s in services)Directory.CreateDirectory(Path.Combine(Server,s.Folder));Write("[1/8] Service directories ready.");foreach(var old in new[]{"CodeName399.GameStash","CodeName399.DebtManager","CodeName399.Kite"})await DeleteService(old);Write("[2/8] Obsolete services removed.");await BackupConfig();Write("[3/8] Configuration backed up.");await Run("dotnet",$"restore \"{Sln}\"","Restore");await Run("dotnet",$"build \"{Sln}\" -c Release --no-restore","Build");Write("[4/8] Solution restored and built.");foreach(var s in services)await Deploy(s);Write("[5/8] All microservices published.");await ValidateGateway();Write("[6/8] Gateway validated.");await RestartAll();Write("[7/8] All microservices restarted and ports verified.");if(selected.ContainsKey("Angular UI") && selected["Angular UI"].Checked) await BuildDeployUi(); else await ConfigureNginx(); Write("[8/8] Nginx configured and restarted.");Write("=== SETUP SUCCESSFUL ===");}catch(Exception ex){Write("[ERROR] "+ex.Message,true);MessageBox.Show(ex.Message,"Setup failed",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{Busy(false);cts.Dispose();cts=null;await RefreshStatus();}}
    async Task BackupConfig(){var d=Path.Combine(Server,"_backups","BeforeSetup");Directory.CreateDirectory(d);foreach(var s in services){var f=Path.Combine(Server,s.Folder,"appsettings.json");if(File.Exists(f))File.Copy(f,Path.Combine(d,s.Name+"-appsettings.json"),true);}var oc=Path.Combine(Server,"Gateway","ocelot.json");if(File.Exists(oc))File.Copy(oc,Path.Combine(d,"Gateway-ocelot.json"),true);await Task.CompletedTask;}
    async Task Deploy(ServiceDef s){Write($"[{s.Name}] Stopping service...");await Stop(s);var project=Path.Combine(Source,s.Project);var dest=Path.Combine(Server,s.Folder);Directory.CreateDirectory(dest);await Run("dotnet",$"publish \"{project}\" -c Release -o \"{dest}\" --no-restore -p:ErrorOnDuplicatePublishOutputFiles=false",s.Name);await EnsureService(s);}
    async Task PublishSelected(){var ss=services.Where(x=>selected[x.Name].Checked).ToList();if(ss.Count==0){MessageBox.Show("Select at least one microservice.");return;}Busy(true);try{foreach(var s in ss)await Deploy(s);}finally{Busy(false);await RefreshStatus();}}
    async Task EnsureService(ServiceDef s){var exe=Path.Combine(Server,s.Folder,s.Exe);if(!File.Exists(exe))throw new Exception($"[{s.Name}] Executable not found: {exe}");var q=await Run("sc.exe",$"query \"{s.Service}\"",s.Name,false);if(q!=0){await Run("sc.exe",$"create \"{s.Service}\" binPath= \"\\\"{exe}\\\" --urls http://127.0.0.1:{s.Port}\" start= auto DisplayName= \"{s.Service}\" obj= LocalSystem",s.Name);}else await Run("sc.exe",$"config \"{s.Service}\" start= auto binPath= \"\\\"{exe}\\\" --urls http://127.0.0.1:{s.Port}\" obj= LocalSystem",s.Name);await Run("sc.exe",$"failure \"{s.Service}\" reset= 86400 actions= restart/5000/restart/10000/restart/30000",s.Name,false);}
    async Task RestartAll(){Busy(true);try{foreach(var s in services){await Stop(s);await Start(s);}}finally{Busy(false);await RefreshStatus();}}
    async Task StopSelected(){var ss=services.Where(x=>selected[x.Name].Checked).ToList();if(ss.Count==0){MessageBox.Show("Select at least one microservice.");return;}Busy(true);try{foreach(var s in ss)await Stop(s);}finally{Busy(false);await RefreshStatus();}}
    async Task Stop(ServiceDef s){await Run("sc.exe",$"stop \"{s.Service}\"",s.Name,false);for(int i=0;i<45;i++){if(await State(s.Service)=="STOPPED"||await State(s.Service)==null)return;await Task.Delay(1000);}var q=await Run("sc.exe",$"queryex \"{s.Service}\"",s.Name,false);}
    async Task Start(ServiceDef s){await Run("sc.exe",$"start \"{s.Service}\"",s.Name,false);for(int i=0;i<45;i++){if(await State(s.Service)=="RUNNING"){if(await Port(s.Port))return;}await Task.Delay(1000);}throw new Exception($"{s.Name} did not start or TCP {s.Port} is not listening.");}
    async Task DeleteService(string name){await Run("sc.exe",$"stop \"{name}\"",name,false);await Run("sc.exe",$"delete \"{name}\"",name,false);}
    async Task ValidateGateway(){var g=services[0];var exe=Path.Combine(Server,g.Folder,g.Exe);if(!File.Exists(exe))throw new Exception("Gateway executable missing.");Write("[Gateway] Validating ocelot.json and startup...");var p=Process.Start(new ProcessStartInfo(exe,"--environment Production --urls http://127.0.0.1:5000"){WorkingDirectory=Path.GetDirectoryName(exe),UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true});if(p==null)throw new Exception("Could not start Gateway validation.");await Task.Delay(3000);if(p.HasExited)throw new Exception("Gateway validation process exited with code "+p.ExitCode);p.Kill(true);}
    async Task ConfigureNginx(){if(!File.Exists(nginx.Text.Trim())){Write("[WARN] Nginx executable not found; skipped.");return;}var root=Path.GetDirectoryName(nginx.Text.Trim())!;var conf=Path.Combine(root,"conf");Directory.CreateDirectory(Path.Combine(root,"logs"));Directory.CreateDirectory(conf);var f=Path.Combine(conf,"nginx.conf");File.WriteAllText(f,$"worker_processes 1;\nerror_log logs/error.log warn;\npid logs/nginx.pid;\nevents {{ worker_connections 1024; }}\nhttp {{ include mime.types; default_type application/octet-stream; sendfile on; keepalive_timeout 65; server {{ listen 80; server_name codename399.com www.codename399.com; root {Server.Replace("\\","/")}/UI; index index.html; location / {{ try_files $uri $uri/ /index.html; }} }} server {{ listen 80; server_name api.codename399.com; location / {{ proxy_pass http://127.0.0.1:5000; proxy_http_version 1.1; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection \"upgrade\"; proxy_connect_timeout 10; proxy_read_timeout 300; proxy_send_timeout 300; }} }} }}");var code=await Run(nginx.Text,"-t -p \""+root+"\\\" -c conf\\nginx.conf",root,"Nginx",false);if(code!=0)throw new Exception("Nginx configuration test failed.");Write("[Nginx] Stopping nginx...");await Run("taskkill","/F /IM nginx.exe",root,"Nginx",false);await Task.Delay(2000);Write("[Nginx] Starting nginx...");Process.Start(new ProcessStartInfo(nginx.Text,$"-p \"{root}\\\" -c conf\\nginx.conf"){WorkingDirectory=root,UseShellExecute=false,CreateNoWindow=true});for(int i=0;i<15;i++){if(await Port(80))break;await Task.Delay(1000);}if(!await Port(80))throw new Exception("Nginx did not start/listen on TCP 80.");await Run("netsh","advfirewall firewall add rule name=\"CodeName399 Nginx HTTP\" dir=in action=allow protocol=TCP localport=80",root,"Nginx",false);await Run("schtasks","/Create /TN \"CodeName399 Nginx\" /SC ONSTART /RU SYSTEM /RL HIGHEST /TR \""+nginx.Text+" -p "+root+" -c conf\\nginx.conf\" /F",root,"Nginx",false);Write("[Nginx] Restarted and TCP 80 verified.");}
    async Task<int> Run(string exe,string args,string tag,bool throwOnError=true)=>await Run(exe,args,Source,tag,throwOnError);
    async Task<int> Run(string exe,string args,string workingDirectory,string tag,bool throwOnError=true){Write($"[{tag}] > {exe} {args}");var psi=new ProcessStartInfo(exe,args){WorkingDirectory=workingDirectory,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};using var p=new Process{StartInfo=psi};p.OutputDataReceived+=(_,e)=>{if(!string.IsNullOrWhiteSpace(e.Data))Write($"[{tag}] {e.Data}");};p.ErrorDataReceived+=(_,e)=>{if(!string.IsNullOrWhiteSpace(e.Data))Write($"[{tag}] {e.Data}",true);};if(!p.Start())throw new Exception("Unable to start "+exe);p.BeginOutputReadLine();p.BeginErrorReadLine();await p.WaitForExitAsync();if(p.ExitCode!=0&&throwOnError)throw new Exception($"[{tag}] exit code {p.ExitCode}");return p.ExitCode;}
    async Task<string?> State(string n)=>await Task.Run(()=>{try{using var s=new ServiceController(n);return s.Status.ToString().ToUpperInvariant();}catch{return null;}});
    async Task<bool> Port(int p)=>await Task.Run(()=>IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpListeners().Any(x=>x.Port==p));
    async Task RefreshStatus(){foreach(var s in services){var st=await State(s.Service);var port=await Port(s.Port);states[s.Name].Text=st=="RUNNING"&&port?$"RUNNING • :{s.Port}":st=="RUNNING"?$"RUNNING • port down":st??"NOT INSTALLED";} if(states.ContainsKey("Angular UI")){states["Angular UI"].Text=await Port(80)?"NGINX RUNNING • UI :80":"NGINX STOPPED";} }
}
